### ISSUE TITLE
Causes touchscreen lag on my device when installed.

### ISSUE THREAD

**Issue by DrEvilFucker** [Paisseon/Satella_ObjC#1]
Tried this app, and after the respring it made the touchscreen laggy.

Swipes were rarely registered, and touches were delayed.
Restarting and re-jailbreaking led to the same result.
Removing the app and doing a respring fixed it right up.

Device; ipad 6th gen, iOS 14.3, Taurine

If you want more data, tell me what to collect.

**Comment by Paisseon** [comment]
Does it lag in the homescreen or just in apps?

**Comment by DrEvilFucker** [comment]
Lags the same amount everywhere.

**Comment by Paisseon** [comment]
The issue might be that it injects into too many things, this caused an error before but I only excluded one process... I don't notice any difference with/without Satella on my devices so I could be completely wrong about the problem, but I'm working on an update that might fix it (hopefully!)

**Comment by DrEvilFucker** [comment]
Can you think of any way to debug this myself?
I assume I'm out of luck without a working copy of xcode though.

IIRC, the lag persisted even after leaving the device alone for a while. Springboard.app and backboardd seemed to have high CPU use in cocoatop too

**Comment by Paisseon** [comment]
Unfortunately not due to a mistake on my part, although disabling Satella.dylib in iCleaner Pro should fix it when not in use

**Comment by Paisseon** [comment]
Does version 2.0 work? I made it so it only injects into user applications and into StoreKit instead of UIKit, so it shouldn't cause any lag
