### ISSUE TITLE
As a tweak for theos-jailed [feature request]

### ISSUE THREAD

**Issue by ZonD80** [Paisseon/Satella_ObjC#12]
Hi. We would like to inject it in apps on non-jailbroken device. Will you have time to rewrite your software as theos-jailed tweak?

**Comment by Paisseon** [comment]
I will try to do this if possible ^^

**Comment by Paisseon** [comment]
It's been a while so just letting you know I'm still working on it alongside Satella2

**Comment by ZonD80** [comment]
Thank you for keeping me updated. Waiting for you

**Comment by Paisseon** [comment]
https://github.com/Paisseon/SatellaJailed

I haven't tried with theos-jailed specifically because I can't get it to work 😅 but it works with iPAPatcher and Sideloadly so the dylib should work :)

**Comment by ZonD80** [comment]
Thank you! I will ask appdb team to enable it for everyone.
