### ISSUE TITLE
Can’t install, requires Orion (iOS 12-13) ? 

### ISSUE THREAD

**Issue by robertybob** [Paisseon/Satella_ObjC#13]
Hey. I’d live to try this tweak, however I’m presented with this with I go to install:

![40C28732-D48C-4A0E-B9A8-8AAC9A1A3CAF](https://user-images.githubusercontent.com/2610395/150698383-d542afdf-f08d-4926-a95c-95f3af9752e9.jpeg)

![1A008D5F-D8A3-43EA-AFF9-17CF3FBB62BE](https://user-images.githubusercontent.com/2610395/150698473-3e7b4f5f-4d5a-4801-8661-d6b81a335588.jpeg)

I’m on iOS 14.8 (unc0ver)

What can I do to resolve this?

**Comment by Paisseon** [comment]
It's a bug with some package managers, if you manually install Orion Runtime (iOS 14) from Chariz repo and then install Satella 2 it should work. Lmk if it doesn't and I'll reopen the issue
