### ISSUE TITLE
Satellaprefs.bundle

### ISSUE THREAD

**Issue by HafezHaidar19** [Paisseon/Satella_ObjC#14]
![image](https://user-images.githubusercontent.com/75736291/155578145-75c5a3d6-6e75-4835-923a-a827cf790e2b.png)

**Comment by Paisseon** [comment]
Are you on an arm64e iOS 13 device? If so, try using the tweak [[TweakSettings]] to get to prefs. For some reason, my compiler doesn't like arm64e + iOS 13 with prefs :/

**Comment by HafezHaidar19** [comment]
Thank you for replying dear !
I realized i had an old version when i opened cydia and when i added your repo i just uninstalled and got satella 2 instead ! I can confirm it works on several video chatting apps “:p note im not a pervert i just experiment with their purchases since they are poorly made”
Cheers and thank you for replying again !

On Feb 25, 2022, at 12:22 AM, Lilly ***@***.***> wrote:

﻿

Are you on an arm64e iOS 13 device? If so, try using the tweak [[TweakSettings]] to get to prefs. For some reason, my compiler doesn't like arm64e + iOS 13 with prefs :/

**Comment by Paisseon** [comment]
Ok, glad its working for you 😊
