### ISSUE TITLE
Can't into Satella option

### ISSUE THREAD

**Issue by Sam20060720** [Paisseon/Satella_ObjC#6]
![image0](https://user-images.githubusercontent.com/40285756/128596685-f7fce5f6-9dbd-41d6-9dd7-3a8a4729a69b.png)

**Comment by geeedoc** [comment]
Having similar preference bundle issues with 2.4 on an iPad Air 3 running iOS 13.3.1. Had to downgrade.

**Comment by Paisseon** [comment]
Super late but this should be fixed in version 2.8.1 (and 2.7.1, and 2.6.1. Basically whenever Naeno reminds me to fix it lol)
