### ISSUE TITLE
Server side don’t work?

### ISSUE THREAD

**Issue by LaxrisPG3D** [Paisseon/Satella_ObjC#7]
Only one app like Crossy roads worked. And the rest were crashing or loading infinite amount of time.

**Comment by imomao** [comment]
impossible, to be honest.

**Comment by Paisseon** [comment]
Correct, server sided purchases can't work. It would require adding app-specific support, which is out of Satella's scope.

**Comment by sodiboo** [comment]
> Correct, server sided purchases can't work. It would require adding app-specific support, which is out of Satella's scope.

Although i agree app-specific support is unreasonable, how about library-specific support? For example with revenuecat, is it possible to spoof its server response and have it work in all apps using that library? Have you thought about implementing anything like this in Satella?

(oops wrong repo, should probably be in Satella 2 instead)
